export const AlbumLookup = {
    '/Type of Products/images/product10.jpg': 'Type of Products/Patio Stone-Oklahoma',
    '/Type of Products/images/product11.jpg': 'Type of Products/Pavers',
    '/Type of Products/images/product13.jpg': 'Type of Products/River Rock',
    '/Type of Products/images/product14.jpg': 'Type of Products/Thin Veneer',
    '/Type of Products/images/product15.jpg': 'Type of Products/Tumbled',
    '/Type of Products/images/product2.jpg': 'Type%20of%20Products/Benches%20&%20Tables',
    '/Type of Products/images/product3.jpg': 'Type of Products/Boulders/',
    '/Type of Products/images/product4.jpg': 'Type of Products/Building Stones-Chop',
    '/Type of Products/images/product5.jpg': 'Type of Products/Drystack',
    '/Type of Products/images/product6.jpg': 'Type of Products/Flagstone',
    '/Type of Products/images/product7.jpg': 'Type of Products/Landscaping Soil, Sand & Gravel',
    '/Type of Project/images/project10.jpg': 'Type of Project/Outdoor Living',
    '/Type of Project/images/project11.jpg': 'Type of Project/Patio',
    '/Type of Project/images/project12.jpg': 'Type of Project/Pavers',
    '/Type of Project/images/project13_tif.jpg': 'Type of Project/Pools',
    '/Type of Project/images/project14.jpg': 'Type of Project/Retaining Walls',
    '/Type of Project/images/project15.jpg': 'Type of Project/Signs',
    '/Type of Project/images/project16.jpg': 'Type of Project/Walkways -Steps',
    '/Type of Project/images/project17.jpg': 'Type of Project/Water Features',
    '/Type of Project/images/project3.jpg': 'Type of Project/Exterior Stone Residential',
    '/Type of Project/images/project4.jpg': 'Type of Project/Firepits',
    '/Type of Project/images/project5.jpg': 'Type of Project/Fireplace',
    '/Type of Project/images/project6.jpg': 'Type of Project/Interior Make-Over',
    '/Type of Project/images/project7.jpg': 'Type of Project/Landscaping',
    '/Type of Project/images/project8.jpg': 'Type of Project/Ledge Look',
    '/Type of Project/images/project9_tif.jpg': 'Type of Project/Outdoor Kitchens',
    
};